// import 'package:flutter/material.dart';
//
// void main() {
//   runApp( FigmaToCodeApp());
// }
//
// // Generated by: https://www.figma.com/community/plugin/842128343887142055/
// class FigmaToCodeApp extends StatelessWidget {
//
//   @override
//   Widget build(BuildContext context) {
//     return MaterialApp(
//       theme: ThemeData.dark().copyWith(
//         scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
//       ),
//       home: Scaffold(
//         body: ListView(children: [
//           Group26(),
//         ]),
//       ),
//     );
//   }
// }
//
// class Group26 extends StatelessWidget {
//   @override
//   Widget build(BuildContext context) {
//     return Column(
//       children: [
//         Container(
//           width: 274.16,
//           height: 73,
//           child: Stack(
//             children: [
//               Positioned(
//                 left: 0.16,
//                 top: 0,
//                 child: Text(
//                   'Drag-Out',
//                   style: TextStyle(
//                     color: Colors.white,
//                     fontSize: 61.11,
//                     fontFamily: 'PoetsenOne',
//                     fontWeight: FontWeight.w400,
//                     height: 0,
//                   ),
//                 ),
//               ),
//               Positioned(
//                 left: 0,
//                 top: 0,
//                 child: Text(
//                   'Drag-Out',
//                   style: TextStyle(
//                     color: Colors.white,
//                     fontSize: 61.11,
//                     fontFamily: 'PoetsenOne',
//                     fontWeight: FontWeight.w400,
//                     height: 0,
//                   ),
//                 ),
//               ),
//             ],
//           ),
//         ),
//       ],
//     );
//   }
// }