name: Update Connection Base

on: [push]

jobs:
  update-base:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set base value based on branch
        run: |
          if [ "${{ github.ref }}" == "refs/heads/master" ]; then
            sed -i 's/static const base = .*/static const base = '\''ambernoak.co.uk\/Fillament\/public'\'';/' lib/core/connection.dart
          elif [ "${{ github.ref }}" == "refs/heads/testing" ]; then
            sed -i 's/static const base = .*/static const base = '\''hqsync.duckdns.org\/Fillament\/public'\'';/' lib/core/connection.dart
          fi

      - name: Check for changes and commit
        run: |
          if [ -n "$(git diff lib/core/connection.dart)" ]; then
            echo "Changes detected. Committing and pushing changes."
            git config --global user.name 'github-actions[bot]'
            git config --global user.email 'github-actions[bot]@users.noreply.github.com'
            git add lib/core/connection.dart
            git commit -m 'Update base URL based on branch'
            git push
          else
            echo "No changes detected. Exiting."
          fi